version: '3.8'

services:
  angular-app:
    build: .
    container_name: angular-ecommerce
    ports:
      - "8080:80"
    restart: always
  express-api:
    image: your-express-api-image
    container_name: express-api
    build:
      context: ./path/to/express-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - MONGO_URI=mongodb://mongodb:27017/yourdbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongodb_data: